// Package idpapi is the local management API of conductor-idp: the
// protocol between conductor's web interface (its "Single sign-on"
// section, the only client) and `conductor-idp serve`. It holds only
// types, validation, framing, presets and a client, so conductor can
// import it without the provider.
//
// Transport: a Unix stream socket (DefaultSocketPath), handed over by
// systemd socket activation (conductor-idp-api.socket: owned by the
// conductor-idp user and the conductor group, mode 0660) or created by
// the service with api.socket_group. The server checks the peer with
// SO_PEERCRED on every connection and admits only the configured UIDs.
// Framing: one request and one response per connection, each one JSON
// object on one line, at most MaxMessageSize bytes. Requests name an
// allowlisted operation; parameters are decoded strictly (unknown fields
// rejected) and validated. Every request carries the acting AD user, which
// the server writes to its hash-chained audit log for every mutation.
//
// Secrets: a confidential client's secret is generated by conductor-idp
// and returned once, in the result of client.create or client.rotate; it
// is stored hashed and never returned again, logged or audited. No other
// secret crosses the socket: signing keys never leave conductor-idp (only
// certificates and key IDs do).
package idpapi

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"regexp"
	"time"
)

// ProtocolVersion is bumped on incompatible changes. Results are decoded
// strictly, so conductor and conductor-idp are upgraded together.
const ProtocolVersion = 1

// DefaultSocketPath is where `conductor-idp serve` listens for conductor.
const DefaultSocketPath = "/run/conductor-idp/api.sock"

// MaxMessageSize bounds one framed message (an SP metadata document of up
// to 1 MiB, base64 inside JSON, fits).
const MaxMessageSize = 4 << 20

// Op names an allowlisted operation.
type Op string

// Operations.
const (
	OpStatus Op = "status"

	OpClientList    Op = "client.list"
	OpClientGet     Op = "client.get"
	OpClientCreate  Op = "client.create"
	OpClientUpdate  Op = "client.update"
	OpClientRotate  Op = "client.rotate"
	OpClientEnable  Op = "client.set_enabled"
	OpClientDelete  Op = "client.delete"
	OpClientPreview Op = "client.preview"

	OpSPList     Op = "sp.list"
	OpSPGet      Op = "sp.get"
	OpSPMetadata Op = "sp.metadata"
	OpSPCreate   Op = "sp.create"
	OpSPUpdate   Op = "sp.update"
	OpSPEnable   Op = "sp.set_enabled"
	OpSPDelete   Op = "sp.delete"
	OpSPPreview  Op = "sp.preview"

	OpKeysList   Op = "keys.list"
	OpKeysRotate Op = "keys.rotate"
	OpKeysCert   Op = "keys.saml_cert"

	OpSettingsGet    Op = "settings.get"
	OpSettingsUpdate Op = "settings.update"

	OpActivity    Op = "activity.summary"
	OpAuditList   Op = "audit.list"
	OpAuditVerify Op = "audit.verify"
)

// Mutating reports whether the operation changes state. Mutations are
// audited with the actor. sp.metadata may fetch a URL but changes nothing;
// it is audited too (it reaches the network for the administrator).
func (o Op) Mutating() bool {
	switch o {
	case OpClientCreate, OpClientUpdate, OpClientRotate, OpClientEnable, OpClientDelete,
		OpSPCreate, OpSPUpdate, OpSPEnable, OpSPDelete, OpKeysRotate, OpSettingsUpdate:
		return true
	}
	return false
}

// Actor is the signed-in conductor user a request is made for.
type Actor struct {
	// User is the AD sAMAccountName.
	User string `json:"user"`
	SID  string `json:"sid"`
	// Session is an opaque identifier of the web session (not the cookie).
	Session string `json:"session"`
	IP      string `json:"ip,omitempty"`
}

// String renders the actor for the audit log.
func (a Actor) String() string {
	s := "conductor:" + a.User
	if a.IP != "" {
		s += "@" + a.IP
	}
	return s
}

// Request is one call.
type Request struct {
	Version int             `json:"version"`
	ID      string          `json:"id"`
	Op      Op              `json:"op"`
	Actor   Actor           `json:"actor"`
	Params  json.RawMessage `json:"params,omitempty"`
	SentAt  time.Time       `json:"sent_at"`
}

// ErrorCode classifies a failed call.
type ErrorCode string

// Error codes.
const (
	CodeBadRequest  ErrorCode = "bad_request"
	CodeInvalid     ErrorCode = "invalid"   // validation failed; Details lists why
	CodeNotFound    ErrorCode = "not_found" // client, SP, key or user unknown
	CodeConflict    ErrorCode = "conflict"  // already exists, stale base version
	CodeUnavailable ErrorCode = "unavailable"
	CodeFailed      ErrorCode = "failed"
	CodeForbidden   ErrorCode = "forbidden"
	CodeVersion     ErrorCode = "version"
)

// Error is the error part of a Response.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
	Details []string  `json:"details,omitempty"`
}

func (e *Error) Error() string { return fmt.Sprintf("conductor-idp: %s: %s", e.Code, e.Message) }

// Response answers a Request with the same ID.
type Response struct {
	Version int             `json:"version"`
	ID      string          `json:"id"`
	OK      bool            `json:"ok"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   *Error          `json:"error,omitempty"`
}

// Params is implemented by every parameter type.
type Params interface{ Validate() error }

// NoParams is used by operations without parameters.
type NoParams struct{}

// Validate implements Params.
func (NoParams) Validate() error { return nil }

// Allowlist maps each operation to a constructor of its parameter type.
var Allowlist = map[Op]func() Params{
	OpStatus: func() Params { return &NoParams{} },

	OpClientList:    func() Params { return &NoParams{} },
	OpClientGet:     func() Params { return &ClientRef{} },
	OpClientCreate:  func() Params { return &ClientCreateParams{} },
	OpClientUpdate:  func() Params { return &ClientUpdateParams{} },
	OpClientRotate:  func() Params { return &ClientRef{} },
	OpClientEnable:  func() Params { return &ClientEnableParams{} },
	OpClientDelete:  func() Params { return &ClientRef{} },
	OpClientPreview: func() Params { return &ClientPreviewParams{} },

	OpSPList:     func() Params { return &NoParams{} },
	OpSPGet:      func() Params { return &SPRef{} },
	OpSPMetadata: func() Params { return &SPMetadataParams{} },
	OpSPCreate:   func() Params { return &SPCreateParams{} },
	OpSPUpdate:   func() Params { return &SPUpdateParams{} },
	OpSPEnable:   func() Params { return &SPEnableParams{} },
	OpSPDelete:   func() Params { return &SPRef{} },
	OpSPPreview:  func() Params { return &SPPreviewParams{} },

	OpKeysList:   func() Params { return &NoParams{} },
	OpKeysRotate: func() Params { return &KeysRotateParams{} },
	OpKeysCert:   func() Params { return &KeysCertParams{} },

	OpSettingsGet:    func() Params { return &NoParams{} },
	OpSettingsUpdate: func() Params { return &SettingsUpdateParams{} },

	OpActivity:    func() Params { return &ActivityParams{} },
	OpAuditList:   func() Params { return &AuditListParams{} },
	OpAuditVerify: func() Params { return &NoParams{} },
}

var (
	idRE   = regexp.MustCompile(`^[A-Za-z0-9_-]{8,64}$`)
	userRE = regexp.MustCompile(`^[^\x00-\x1f]{1,256}$`)
	sidRE  = regexp.MustCompile(`^S-1-[0-9]+(-[0-9]+){1,15}$`)
)

// NewRequest builds a validated request.
func NewRequest(id string, op Op, actor Actor, params Params) (Request, error) {
	if params == nil {
		params = NoParams{}
	}
	raw, err := json.Marshal(params)
	if err != nil {
		return Request{}, err
	}
	req := Request{Version: ProtocolVersion, ID: id, Op: op, Actor: actor, Params: raw, SentAt: time.Now().UTC()}
	if _, err := req.Decode(); err != nil {
		return Request{}, err
	}
	return req, nil
}

// Decode validates the envelope and decodes the typed parameters.
func (r Request) Decode() (Params, error) {
	if r.Version != ProtocolVersion {
		return nil, &Error{Code: CodeVersion, Message: fmt.Sprintf("protocol version %d, want %d", r.Version, ProtocolVersion)}
	}
	if !idRE.MatchString(r.ID) {
		return nil, &Error{Code: CodeBadRequest, Message: "invalid request id"}
	}
	if !userRE.MatchString(r.Actor.User) || r.Actor.Session == "" || len(r.Actor.Session) > 128 || len(r.Actor.IP) > 64 {
		return nil, &Error{Code: CodeBadRequest, Message: "the actor (user and session) is required"}
	}
	if !sidRE.MatchString(r.Actor.SID) {
		return nil, &Error{Code: CodeBadRequest, Message: "the actor SID is invalid"}
	}
	mk, ok := Allowlist[r.Op]
	if !ok {
		return nil, &Error{Code: CodeBadRequest, Message: fmt.Sprintf("operation %q is not allowlisted", r.Op)}
	}
	p := mk()
	params := r.Params
	if len(params) == 0 || string(params) == "null" {
		params = json.RawMessage("{}")
	}
	dec := json.NewDecoder(bytes.NewReader(params))
	dec.DisallowUnknownFields()
	if err := dec.Decode(p); err != nil {
		return nil, &Error{Code: CodeBadRequest, Message: "params: " + err.Error()}
	}
	if dec.More() {
		return nil, &Error{Code: CodeBadRequest, Message: "params: trailing data"}
	}
	if err := p.Validate(); err != nil {
		return nil, &Error{Code: CodeBadRequest, Message: err.Error()}
	}
	return p, nil
}

// OKResponse builds a successful response.
func OKResponse(id string, result any) (Response, error) {
	raw, err := json.Marshal(result)
	if err != nil {
		return Response{}, err
	}
	return Response{Version: ProtocolVersion, ID: id, OK: true, Result: raw}, nil
}

// ErrorResponse builds a failed response.
func ErrorResponse(id string, e *Error) Response {
	return Response{Version: ProtocolVersion, ID: id, Error: e}
}

// WriteMessage frames v as one JSON line.
func WriteMessage(w io.Writer, v any) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	if len(b)+1 > MaxMessageSize {
		return ErrTooLarge
	}
	_, err = w.Write(append(b, '\n'))
	return err
}

// ErrTooLarge is returned for a message beyond MaxMessageSize.
var ErrTooLarge = errors.New("idpapi: message too large")

// ReadMessage reads one framed message into v (unknown fields rejected).
func ReadMessage(r *bufio.Reader, v any) error {
	var line []byte
	for {
		chunk, isPrefix, err := r.ReadLine()
		if err != nil {
			return err
		}
		line = append(line, chunk...)
		if len(line) > MaxMessageSize {
			return ErrTooLarge
		}
		if !isPrefix {
			break
		}
	}
	dec := json.NewDecoder(bytes.NewReader(line))
	dec.DisallowUnknownFields()
	return dec.Decode(v)
}
